In [1]:
import os
import json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
# Remember to install sklearn with
# pip install -U scikit-learn

import sklearn

In [43]:
features = [
    'bathrooms', 
    'bedrooms', 
    'latitude', 
    'longitude', 
    'price',
    'Special Characters',
    'Numbers', 
    'StopWord',
    'Uppercase',
]

In [44]:
df = pd.read_json('cleaned_train.json')

In [45]:
df_X = df.drop('interest_level', axis=1)
df_y = df['interest_level']

In [46]:
df_X = df.drop('interest_level', axis=1)
df_X = df_X.drop('description', axis=1)
df_X = df_X.drop('display_address', axis=1)
df_X = df_X.drop('street_address', axis=1)
df_X = df_X.drop('features', axis=1)
df_X = df_X.drop('created', axis=1)
df_X = df_X.drop('listing_id', axis=1)

In [47]:
from sklearn.model_selection import KFold # import KFold

kf = KFold(n_splits=5) # Define the split - into 5 folds 
kf.get_n_splits(df_X) # returns the number of splitting iterations in the cross-validator

KFold(n_splits=5, random_state=None, shuffle=False)

KFold(n_splits=5, random_state=None, shuffle=False)

In [48]:

#scores = cross_val_score(clf, df_X, df_y, cv=5)

# Decision tree

In [49]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO 
from IPython.display import Image 
from pydot import graph_from_dot_data
import pandas as pd
import numpy as np

In [50]:
df_y2 = pd.get_dummies(df_y)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(df_X, df_y2, random_state=1)

In [52]:
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [53]:
# dot_data = StringIO()

# export_graphviz(dt, out_file=dot_data, feature_names=features)

# (graph, ) = graph_from_dot_data(dot_data.getvalue())
# Image(graph.create_png())

In [54]:
y_pred = dt.predict(X_test)
print("Score: ", metrics.accuracy_score(y_test, y_pred))

Score:  0.6292308947067939


In [55]:
scores = cross_val_score(estimator=dt, X=df_X, y=df_y, cv=10, n_jobs=4)

In [56]:
scores

array([0.64077472, 0.64620718, 0.64987765, 0.65619902, 0.65844209,
       0.63764274, 0.64702284, 0.63641925, 0.62948613, 0.62826264])

In [57]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted')

0.6413913650904929

In [58]:
import pandas as pd
from sklearn import preprocessing

x = df_X.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_X_normalized = pd.DataFrame(x_scaled)

In [59]:
df_X_normalized

0      1         2         3         4         5         6  \
0      0.10  0.125  0.031114  0.866763  0.157102  0.176991  0.086957   
1      0.10  0.250  0.040518  0.865942  0.250417  0.079646  0.086957   
2      0.10  0.250  0.041958  0.866377  0.230087  0.097345  0.086957   
3      0.15  0.375  0.031973  0.867275  0.197094  0.070796  0.043478   
4      0.10  0.000  0.038800  0.865848  0.183430  0.053097  0.043478   
...     ...    ...       ...       ...       ...       ...       ...   
49036  0.10  0.000  0.043467  0.865067  0.142105  0.000000  0.000000   
49037  0.10  0.375  0.061880  0.867405  0.183763  0.026549  0.043478   
49038  0.10  0.250  0.056424  0.866588  0.156769  0.026549  0.043478   
49039  0.10  0.250  0.039009  0.864618  0.276745  0.079646  0.043478   
49040  0.10  0.375  0.042399  0.865987  0.282410  0.070796  0.086957   

              7         8  
0      0.041885  0.029980  
1      0.209424  0.047302  
2      0.146597  0.041306  
3      0.041885  0.040640  
4      0.000000  0.023984  
...         ...       ...  
49036  0.089005  0.004664  
49037  0.198953  0.010660  
49038  0.083770  0.007995  
49039  0.151832  0.016656  
49040  0.052356  0.070620  

[49041 rows x 9 columns]

In [60]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_X_normalized, df_y2, random_state=1)

In [61]:
dt_normal = DecisionTreeClassifier()

dt_normal.fit(X_train2, y_train2)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [62]:
y_pred2 = dt_normal.predict(X_test2)
print("Score: ", metrics.accuracy_score(y_test2, y_pred2))

Score:  0.6311883206916239


In [63]:
scores = cross_val_score(estimator=dt_normal, X=df_X, y=df_y, cv=5, n_jobs=4)
scores

array([0.64950556, 0.65436378, 0.6437602 , 0.63305465, 0.62714111])

In [64]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV

parameters = {'max_depth':range(3,20)}
tree_cv = GridSearchCV(tree.DecisionTreeClassifier(), parameters, n_jobs=4)
tree_cv.fit(X=X_train2, y=y_train2)
tree_model = tree_cv.best_estimator_
print (tree_cv.best_score_, tree_cv.best_params_) 

0.6673463839042959 {'max_depth': 4}


In [65]:
y_pred_cv = tree_cv.predict(X_test2)
print("Score: ", metrics.accuracy_score(y_test2, y_pred_cv))

Score:  0.6820813962972025


In [78]:
scores = cross_val_score(estimator=tree_cv, X=df_X_normalized, y=df_y, cv=5, n_jobs=4)
scores
df_y

4         medium
6            low
9         medium
10        medium
15           low
           ...  
123998       low
124000       low
124002    medium
124008    medium
124009      high
Name: interest_level, Length: 49041, dtype: object

# SVM

In [69]:
# Necessary imports: 
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn import svm

from sklearn.model_selection import train_test_split

In [76]:
svm_clf = svm.SVC(kernel='linear', C=1)
df_y_num = df_y

X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(
    df_X_normalized, 
    df_y_num, 
    random_state=1,
)

svm_clf.fit(X_train_svm, y_train_svm)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [77]:
y_pred_svm = svm_clf.predict(X_test_svm)
print("Score: ", metrics.accuracy_score(y_test_svm, y_pred_svm))

Score:  0.6988010765842917


In [79]:
scores = cross_val_score(estimator=tree_cv, X=df_X_normalized, y=df_y, cv=5, n_jobs=4)
scores

array([0.70384341, 0.70656607, 0.70350734, 0.6975938 , 0.69677814])

SVM hyperparameter tuning

In [80]:
param_grid = {
    'C': [0.1,1, 10, 100], 
    'gamma': [1,0.1,0.01,0.001],
    'kernel': ['rbf', 'poly', 'sigmoid']
}

In [82]:
grid_svm = GridSearchCV(svm.SVC(),param_grid,refit=True,verbose=2)
grid_svm.fit(X_train_svm, y_train_svm)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  26.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   26.0s remaining:    0.0s


[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  25.8s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  25.7s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  26.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  25.7s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] ...................... C=0.1, gamma=1, kernel=poly, total=  15.5s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] ...................... C=0.1, gamma=1, kernel=poly, total=  14.8s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] ...................... C=0.1, gamma=1, kernel=poly, total=  15.0s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] .

[CV] ............... C=0.1, gamma=0.001, kernel=sigmoid, total=  26.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  36.5s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  32.6s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  32.5s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  32.9s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  31.9s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV] ........................ C=1, gamma=1, kernel=poly, total=  32.0s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV] .

[CV] ................. C=1, gamma=0.001, kernel=sigmoid, total=  28.1s
[CV] C=1, gamma=0.001, kernel=sigmoid ................................
[CV] ................. C=1, gamma=0.001, kernel=sigmoid, total=  25.9s
[CV] C=1, gamma=0.001, kernel=sigmoid ................................
[CV] ................. C=1, gamma=0.001, kernel=sigmoid, total=  25.9s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........................ C=10, gamma=1, kernel=rbf, total= 1.5min
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........................ C=10, gamma=1, kernel=rbf, total= 1.4min
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........................ C=10, gamma=1, kernel=rbf, total= 1.4min
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........................ C=10, gamma=1, kernel=rbf, total= 1.4min
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] .

[CV] ................ C=10, gamma=0.001, kernel=sigmoid, total=  25.8s
[CV] C=10, gamma=0.001, kernel=sigmoid ...............................
[CV] ................ C=10, gamma=0.001, kernel=sigmoid, total=  25.8s
[CV] C=10, gamma=0.001, kernel=sigmoid ...............................
[CV] ................ C=10, gamma=0.001, kernel=sigmoid, total=  25.8s
[CV] C=10, gamma=0.001, kernel=sigmoid ...............................
[CV] ................ C=10, gamma=0.001, kernel=sigmoid, total=  25.8s
[CV] C=10, gamma=0.001, kernel=sigmoid ...............................
[CV] ................ C=10, gamma=0.001, kernel=sigmoid, total=  25.7s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] ....................... C=100, gamma=1, kernel=rbf, total= 4.6min
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] ....................... C=100, gamma=1, kernel=rbf, total= 5.3min
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .

[CV] .................. C=100, gamma=0.001, kernel=poly, total=  12.8s
[CV] C=100, gamma=0.001, kernel=poly .................................
[CV] .................. C=100, gamma=0.001, kernel=poly, total=  12.8s
[CV] C=100, gamma=0.001, kernel=sigmoid ..............................
[CV] ............... C=100, gamma=0.001, kernel=sigmoid, total=  26.0s
[CV] C=100, gamma=0.001, kernel=sigmoid ..............................
[CV] ............... C=100, gamma=0.001, kernel=sigmoid, total=  25.9s
[CV] C=100, gamma=0.001, kernel=sigmoid ..............................
[CV] ............... C=100, gamma=0.001, kernel=sigmoid, total=  25.7s
[CV] C=100, gamma=0.001, kernel=sigmoid ..............................
[CV] ............... C=100, gamma=0.001, kernel=sigmoid, total=  25.7s
[CV] C=100, gamma=0.001, kernel=sigmoid ..............................
[CV] ............... C=100, gamma=0.001, kernel=sigmoid, total=  25.7s


[Parallel(n_jobs=1)]: Done 240 out of 240 | elapsed: 222.0min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [83]:
grid_cv = grid_svm.best_estimator_
print (grid_svm.best_score_, grid_svm.best_params_) 

0.6911636759108211 {'C': 100, 'gamma': 1, 'kernel': 'rbf'}


Kaggle conversion

In [116]:
test_df = pd.read_json('./test.json')


In [118]:
test_df.shape

(74659, 14)

In [119]:
df_clean3 = test_df[
        test_df.apply(
            lambda x: x['street_address']!= '' \
            or x['street_address'] != '0' \
            or x['street_address'] != 0 \
            or x['street_address'] != 0.0, axis = 1
        )
]

In [120]:
df_clean4 = df_clean3.drop(columns=['building_id', 'manager_id', 'photos'])

In [121]:
df_clean4.shape

(74659, 11)

In [115]:
test_df_X = df_clean4.drop('description', axis=1)
test_df_X = test_df_X.drop('display_address', axis=1)
test_df_X = test_df_X.drop('street_address', axis=1)
test_df_X = test_df_X.drop('features', axis=1)
test_df_X = test_df_X.drop('created', axis=1)
test_df_X = test_df_X.drop('listing_id', axis=1)

In [ ]:
test_df_listings = df_clean